### ISSUE TITLE
Bravery panel tracking issue

### ISSUE THREAD

**Issue by luixxiul** [luixxiul/browser-laptop#3]
TODOs:

- [x] Add compact panel
- [x] Replace test selectors with `data-test-id`s
- [x] Replace LESS styles with Aphrodite
- [x] Replace `[css(...)]` with `css(...)` if all elements inside `cx` is `css(...)`
- ~~[ ] Set text-overflow to `Fingerprinting Protection (?)`~~
- [ ] feature to save the advanced control open/closed state
- [ ] feature to avoid opening the advanced control panel when you click the counter
